# Conversion
markdown:         redcarpet
highlighter:      pygments
pygments: true

exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock

# Permalinks
permalink:        pretty

#predefine variable
title:            Armin
description:      '『任何一把剃刀都自有它的哲学』'
header:           'How Come'
url:              www.arminalter.com

# paginate
paginate:         3

author:
  name:           'Armin'
  email:           min4450@outlook.com


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post" # previously `post` in Jekyll 2.2. now is posts
    values:
      layout: "post"